version: '0.1'
services:
  web:
    image: "ptt9881/be_django:latest"
    # command: ["executable", "arg"]
    command: python manage.py runserver 0.0.0.0:8000
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    # volumes:
    #   - .:/Django_C4F
    depends_on:
      - db
  db:
    image: "postgres:latest"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: Django_C4F
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  adminer:
    image: "adminer:latest"
    restart: always
    ports:
      - 8080:8080

  redis:
    image: "redis/redis-stack-server:latest"
    container_name: redis-stack-server
